spring:
  data:
    mongodb:
      uri: mongodb+srv://mergimjanuzi:iRtTLTjZt8Jmw0z7@mergimcluster.ffqai.mongodb.net/

jwt:
  secret: hfaiehfisehfosndfejndfeswljrfeowfnjehwbewios4ngvhtrwglp4rkledf
  expirationMs: 360000000.